# Skip if requirements are not found.
if (( $+commands[ssh-agent] )); then
	# Set the path to the SSH directory.
	_ssh_dir="$HOME/.ssh"

	# Set the path to the environment file if not set by another module.
	_ssh_agent_env="${_ssh_agent_env:-${TMPDIR:-/tmp}/ssh-agent.env.$UID}"

	# Set the path to the persistent authentication socket.
	_ssh_agent_sock="${TMPDIR:-/tmp}/ssh-agent.sock.$UID"

	# Start ssh-agent if not started.
	if [[ ! -S "$SSH_AUTH_SOCK" ]]; then
		# Export environment variables.
		source "$_ssh_agent_env" 2> /dev/null

		# Start ssh-agent if not started.
		if ! ps -U "$LOGNAME" -o pid,ucomm | grep -q -- "${SSH_AGENT_PID:--1} ssh-agent"; then
			eval "$(ssh-agent | sed '/^echo /d' | tee "$_ssh_agent_env")"
		fi
	fi

	# Create a persistent SSH authentication socket.
	if [[ -S "$SSH_AUTH_SOCK" && "$SSH_AUTH_SOCK" != "$_ssh_agent_sock" ]]; then
		ln -sf "$SSH_AUTH_SOCK" "$_ssh_agent_sock"
		export SSH_AUTH_SOCK="$_ssh_agent_sock"
	fi
fi

# # Start SSH agent if not running and not using gnome-keyring
# $(ps aux | grep $(whoami) | grep gnome-keyring | grep -v grep > /dev/null;)
# GK=$?
# if [[ "$GK" -ne 0 ]]; then
#   if ! ps aux | grep $(whoami) | grep ssh-agent | grep -v grep >/dev/null; then
#     echo "Starting ssh-agent"
#     eval $(ssh-agent -a $SSH_AUTH_SOCK -s)
#   fi
# fi

[[ -d "$HOME/go" ]] && export GOPATH=$HOME/go
[[ -n "$GOPATH" ]] && export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

alias vic='cd ~/go/src/github.com/vmware/vic'
alias product='cd ~/go/src/github.com/vmware/vic-product'

alias la='ls -A'
alias ll='ls -alhF'
alias l='ls -alhF'

# antigen
use_antigen=false
if [[ -a ~/.antigen/antigen.zsh ]]; then
  source ~/.antigen/antigen.zsh
  use_antigen=true
elif [[ -a /usr/share/zsh-antigen/antigen.zsh ]]; then
  source /usr/share/zsh-antigen/antigen.zsh
  use_antigen=true
fi

if [[ $use_antigen ]]; then
  antigen use oh-my-zsh

  antigen bundle zsh-users/zsh-syntax-highlighting
  antigen bundle zsh-users/zsh-history-substring-search
  antigen bundle zsh-users/zsh-completions
  antigen bundle docker
  antigen bundle golang
  antigen bundle gitfast

  antigen theme pygmalion
  antigen apply
fi

# docker version manager
if [[ -f ~/.dvm/dvm.sh ]]; then
  source ~/.dvm/dvm.sh
fi
